apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache
  labels:
    app: apache
  namespace: brightspot8
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apache
  template:
    metadata:
      labels:
        app: apache
    spec:
      containers:
        - name: apache
          image: ankitjagtap/brightspot-apache:latest
          ports:
            - containerPort: 80
            - containerPort: 443
          volumeMounts:
            - name: storage-data
              mountPath: /var/www/localhost/htdocs/storage
        
      volumes:
        - name: storage-data
          persistentVolumeClaim:
            claimName: storage-data-pvc
