apiVersion: v1
kind: Pod
metadata:
  name: initdb-dummy-pod
  namespace: brightspot8
spec:
  containers:
    - name: file-uploader
      image: alpine/git
      command: ["/bin/sh", "-c", "while true; do sleep 30; done;"]
      volumeMounts:
        - name: mysql-initdb
          mountPath: /docker-entrypoint-initdb.d
        - name: code
          mountPath: /code
        - name: aws-credentials
          mountPath: /etc/aws
        - name: storage
          mountPath: /servers/tomcat/storage
        - name: solr-data
          mountPath: /var/solr/data/collection1/data
        
  volumes:
    - name: mysql-initdb
      persistentVolumeClaim:
        claimName: mysql-initdb-pvc
    - name: code
      persistentVolumeClaim:
        claimName: tomcat-code-pvc
    - name: aws-credentials
      persistentVolumeClaim:
        claimName: aws-credentials-pvc
    - name: storage
      persistentVolumeClaim:
        claimName: storage-data-pvc
    - name: solr-data
      persistentVolumeClaim:
         claimName: solr-data-pvc
