apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  namespace: brightspot8
  name: k8s-gp2
provisioner: ebs.csi.aws.com
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Delete
parameters:
  type: gp2
  fsType: ext4 # Optional: ensures ext4 filesystem is used for volumes
