apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: storage-data-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: k8s-gp2

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: solr-data-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: k8s-gp2

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-data-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: k8s-gp2

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-logs-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: k8s-gp2

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-initdb-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: k8s-gp2

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tomcat-code-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: k8s-gp2
