apiVersion: apps/v1
kind: Deployment
metadata:
  name: solr
  labels:
    app: solr
  namespace: brightspot8
spec:
  replicas: 1
  selector:
    matchLabels:
      app: solr
  template:
    metadata:
      labels:
        app: solr
    spec:
      containers:
        - name: solr
          image: ankitjagtap/brightspot-training-solr:latest
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: solr-data
              mountPath: /var/solr/data/collection1/data
      volumes:
        - name: solr-data
          persistentVolumeClaim:
            claimName: solr-data-pvc
