name: Build

on:
  push:
    branches:
      - develop
      - exercise/*

  pull_request:
    branches:
      - develop

jobs:
  build-brightspot:
    uses: perfectsense/brightspot-github-actions-workflows/.github/workflows/brightspot-build.yml@v1
    secrets: inherit
    with:
      node-version: '16.20.1'
      runs-on: 'ubuntu-20.04'
